id: I71741B11
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:03:43+00:00'
last_modified: '2022-06-08T08:51:06.328375+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4999
  title: སྐད་ཡིག་འདེམ་སྦྱོང་བསླབ་ཚན་གྱི་གཙོ་གནད་དང་དཀའ་གནད་ཀུན་བཏུས་ཀྱི་དྲི་བ་དྲིས་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    AA39:
      image_group_id: I3CN8653
      title: ''
      total_pages: 184
      order: 1
      base_file: AA39.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
